### ISSUE TITLE
Path parameters and i18n

### ISSUE THREAD

**Issue by saeub** [snok/django-swagger-tester#115]
We have an internationalized API where the language is provided in the path like this:

- `/de/api/objects/{id}`
- `/en/api/objects/{id}`

It would be nice to document this in the OpenAPI like this:

```yaml
paths:
  /{lang}/api/objects/{id}:
    get:
      parameters:
        - name: lang
          in: path
          ...
```

However, since we're using `django.conf.urls.i18n.i18n_patterns` to generate the URL patterns for all available languages, `lang` isn't an actual parameter in the Django URL pattern. `django_swagger_tester` seems to assume that all parameters in the YAML schema are also parameters in the Django URL pattern and raises an exception:

```
Error: Unsuccessfully tried to index the OpenAPI schema by `/de/api/objects/123`.

For debugging purposes, other valid routes include: /{lang}/api/objects, /{lang}/api/objects/{id}.
```

The only solution I found to this is to hard-code all available languages in the schema:

```yaml
paths:
  /de/api/objects/{id}:
    ...
  /en/api/objects/{id}:
    ...
  ...
```

But this is obviously not very nice, since the response schemas always look the same. Is there another way to do this? Did I miss something?

For example, would it possible for us to tell `validate_response()` which value to expect for the additional `lang` parameter in the schema and add it to the [`kwargs`](https://github.com/snok/django-swagger-tester/blob/6b70869216adf790025c793570d91e88152564db/django_swagger_tester/utils.py#L188) that were returned by Django's `resolve()` function, so it can resolve `/de/api/objects/{id}` into `/{lang}/api/objects/{id}` to get the correct route for indexing the schema?

Thanks!

**Comment by sondrelg** [comment]
This is interesting. I agree you should be able to document the endpoint like your first example.

Do you think internationalised routes is something that could be auto-detected? **If** we had reason to believe that everyone would document their endpoints like `/{lang}/api/objects/{id}` (I wonder how swagger-generators behave), I would think that this is something we could default to. If not, maybe we could create a setting to treat the locale-part of the route as a parameter.

Would you be willing to submit a PR with the minimal amount of code required to set up similar paths in the demo project?

**Comment by saeub** [comment]
Thanks for the quick reply @sondrelg!

I'm not entirely familiar with how Django generates those routes, so I'm not sure how deep we would have to dig to detect the internationalized ones. Also, I haven't seen this pattern of using language codes in URLs to control response language used a lot in API specifications generally, and I don't know if there is a convention.

It seems that `drf_yasg` only recognizes the routes for the language preferred by the user's browser (or the default set in `settings.py`) and therefore only shows `/de/api/objects/{id}`. In our case, we cannot use any automatic generators anyway, and showing which languages are available would be nice (for example with an `enum` parameter).

I'm happy to submit a PR that sets up i18n in the demo project as soon as I find the time.

**Comment by sondrelg** [comment]
We do have access to the projects settings; is there no standard setting (a list of supported languages for example) we could check for to get the list of path locales? That could perhaps get us part of the way there.

If not I guess we could just add a complete mapping of paths youd want to override to the package settings, or a kwarg to pass to the individual validate-response call.

**Comment by sondrelg** [comment]
After looking at the Django docs for a little bit, I see the routing in Django is performed based on the `LocaleMiddleware` and that the base paths provided to the `i18n_patterns` more or less by invoking

```python
from django.utils import translation

translation.get_language() 
```

This is just me trying to think out loud, but I think the easiest way to solve this might be what you originally suggested; to create a kwarg for substituting this part of your route. Something like 

```python
validate_response(..., substitute_path_section=('en-us', '{lang}')
```

which would let you substitute the path with the general parameter you used to document the endpoint.

The only thing we need is an internationalised route (but I've done part of that work in the `i18n` branch if you want to correct and build on that) and to document the static schema in `demo/static_schemas/openapi-schema.yml`.
