### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [snok/django-swagger-tester#60]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 0.0.8. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary openapi-tester -w /tmp/ext openapi-tester==0.0.8
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting openapi-tester==0.0.8
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/80b/bd7c93d28b10e/openapi-tester-0.0.8.tar.gz (20 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-z6cpb7yr/openapi-tester/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-z6cpb7yr/openapi-tester/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-z6cpb7yr/openapi-tester/pip-egg-info
         cwd: /tmp/pip-wheel-z6cpb7yr/openapi-tester/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-z6cpb7yr/openapi-tester/setup.py", line 10, in <module>
        with open('CHANGELOG.rst') as changelog_file:
    FileNotFoundError: [Errno 2] No such file or directory: 'CHANGELOG.rst'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by JonasKs** [comment]
Version `0.0.8` is an alpha version during development. There is no reason to not be on a `1.x` build, so I’m closing this issue. Feel free to open a new one if you have issues with the stable version.

**Comment by thatch** [comment]
0.0.8 is the latest version you have on pypi...

**Comment by JonasKs** [comment]
https://pypi.org/project/django-swagger-tester/, `django-swagger-tester 1.0.3` @thatch

**Comment by thatch** [comment]
Ah, I was using https://pypi.org/project/openapi-tester/ whose homepage redirects to this repo, and only has up to 0.0.8.  I suppose that's abandoned?  Your 1.0.3 passes this check.

**Comment by JonasKs** [comment]
You’re right, the project got renamed during alpha. I’ll ping @sondrelg, he’s in charge of PyPi for this project. Might want to mark it as deprecated or delete it entirely.

**Comment by sondrelg** [comment]
The old pypi project has now been deleted.
